### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by tedzyc** [xiazdong/RecyclerViewDemo#1]
报这个：Execution failed for task ':app:mergeDebugResources'. > -1

 studio用的2.2.2

**Comment by mundane799699** [comment]
我也编译不过, 和上面同样的错误

**Comment by hq001a** [comment]
我也编译不过, 和上面同样的错误..................resource有什么问题吗？

**Comment by xinpengfei520** [comment]
把res目录下的assets目录移动main目录下即可...

**Comment by wying111** [comment]
我这里没发现assets啊
Error:Execution failed for task ':app:mergeDebugResources'.
> java.lang.ArrayIndexOutOfBoundsException (no error message)
这个错误

**Comment by AltairT** [comment]
xinpengfei520 正解,要在Project视图下才能看到assets目录,app视图下看不到.assets里面有个gif动图,应该是github 文档用的,和项目无关.

**Comment by look0089** [comment]
将assets整个目录删除也行，里面是gif动图，和项目无关
Remove the assets folder including gif
