### ISSUE TITLE
进入demo6报错

### ISSUE THREAD

**Issue by JerryMissTom** [xiazdong/RecyclerViewDemo#3]
manifest中的主题应该设置为android:theme="@style/AppTheme.NoActionBar"

**Comment by AltairT** [comment]
主题的问题,在AndroidManifest.xml更改Demo6的主题为AppTheme.NoActionBar
<activity
            android:name=".demo6.Activity6"
            android:theme="@style/AppTheme.NoActionBar"/>

**Comment by JerryMissTom** [comment]
已经解决了。 @AltairT
